# Generated by Django 5.0.1 on 2024-01-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='totalHour',
            field=models.IntegerField(null=True),
        ),
    ]
