# Generated by Django 5.0.2 on 2024-02-15 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_useraccount_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='branch',
            field=models.CharField(choices=[('DB', 'สาขาวิชาธุรกิจดิจิทัล'), ('IT', 'สาขาวิชาเทคโนโลยีสารสนเทศ'), ('GIS', 'สาขาวิชาภูมิสารสนเทศศาสตร์'), ('CS', 'สาขาวิชาวิทยาการคอมพิวเตอร์'), ('DSA', 'สาขาวิชาวิทยาการข้อมูลและการประยุกต์'), ('CPE', 'สาขาวิชาวิศวกรรมคอมพิวเตอร์'), ('SE', 'สาขาวิชาวิศวกรรมซอฟต์แวร์'), ('CG', 'สาขาวิชาคอมพิวเตอร์กราฟิกและมัลติมีเดีย'), ('OFFICE', 'สำนักงานคณะ'), ('-', '-')], max_length=40, null=True),
        ),
    ]
