# Generated by Django 5.0.1 on 2024-02-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_activity_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='isSelected',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
