# Generated by Django 5.0.1 on 2024-01-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_totalhour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='branch',
            field=models.CharField(blank=True, choices=[('DB', 'สาขาวิชาธุรกิจดิจิทัล'), ('IT', 'สาขาวิชาเทคโนโลยีสารสนเทศ'), ('GIS', 'สาขาวิชาภูมิสารสนเทศศาสตร์'), ('CS', 'สาขาวิชาวิทยาการคอมพิวเตอร์'), ('DSA', 'สาขาวิชาวิทยาการข้อมูลและการประยุกต์'), ('CPE', 'สาขาวิชาวิศวกรรมคอมพิวเตอร์'), ('SE', 'สาขาวิชาวิศวกรรมซอฟต์แวร์'), ('CG', 'สาขาวิชาคอมพิวเตอร์กราฟิกและมัลติมีเดีย'), ('OFFICE', 'สำนักงานคณะ')], max_length=40, null=True),
        ),
    ]
