# Generated by Django 5.0.2 on 2024-02-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_useraccount_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='updateDate',
            field=models.DateTimeField(),
        ),
    ]
